daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - security
  - do-not-close
staleLabel: no-response
markComment: >
  This issue has been marked as stale because it has not had
  recent activity. The bot will close the issue if no further action occurs.
closeComment: false
