name: Run e2e tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: [ 1.18.16, 1.19.8, 1.20.4 ]
    name: k8s ${{ matrix.k8s }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: actions/checkout@master
    - name: Run tests
      env:
        K8S_VERSION: ${{ matrix.k8s }}
        TTS_TOKEN: ${{ secrets.TTS_TOKEN }}
      run: |
        export HCLOUD_TOKEN=$(./script/get-token.sh)
        cat resp.json
        go test $(go list ./... | grep e2etests) -v -timeout 60m
        ./script/delete-token.sh $HCLOUD_TOKEN
